project_id = "duhnpobrykwdhiqtoupo"

[functions.mavie-chat]
verify_jwt = false

[functions.send-invoice]
verify_jwt = false

[functions.knowledge-search]
verify_jwt = false

[functions.escalate-chat]
verify_jwt = false